//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinLogin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categories
    {
        public Categories()
        {
            this.Questions = new HashSet<Questions>();
        }
    
        public int id_category { get; set; }
        public string name_category { get; set; }
        public int id_subject_cat { get; set; }
    
        public virtual Subjects Subjects { get; set; }
        public virtual ICollection<Questions> Questions { get; set; }
    }
}
