//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinLogin
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogStudents
    {
        public int id_log { get; set; }
        public string name_stud { get; set; }
        public int id_group_st { get; set; }
        public System.DateTime date_exam { get; set; }
        public int id_subject_log { get; set; }
    
        public virtual Groups Groups { get; set; }
        public virtual Subjects Subjects { get; set; }
    }
}
