//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinLogin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questions
    {
        public int id_question { get; set; }
        public int id_subject_ques { get; set; }
        public int id_category_ques { get; set; }
        public string text_quesation { get; set; }
        public string pathToPicture { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Subjects Subjects { get; set; }
    }
}
