//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinLogin
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectOfTeacher
    {
        public int id_sot { get; set; }
        public int id_teacher_sot { get; set; }
        public int id_subject_sot { get; set; }
        public bool active { get; set; }
    
        public virtual Subjects Subjects { get; set; }
        public virtual Teachers Teachers { get; set; }
    }
}
