//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinLogin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subjects
    {
        public Subjects()
        {
            this.Categories = new HashSet<Categories>();
            this.LogStudents = new HashSet<LogStudents>();
            this.Questions = new HashSet<Questions>();
            this.SubjectOfTeacher = new HashSet<SubjectOfTeacher>();
        }
    
        public int id_subject { get; set; }
        public string name_subject { get; set; }
        public Nullable<int> quantity_questions_of_tiket { get; set; }
    
        public virtual ICollection<Categories> Categories { get; set; }
        public virtual ICollection<LogStudents> LogStudents { get; set; }
        public virtual ICollection<Questions> Questions { get; set; }
        public virtual ICollection<SubjectOfTeacher> SubjectOfTeacher { get; set; }
    }
}
