//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinLogin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teachers
    {
        public Teachers()
        {
            this.SubjectOfTeacher = new HashSet<SubjectOfTeacher>();
        }
    
        public int id_teacher { get; set; }
        public string name_tch { get; set; }
        public string login_tch { get; set; }
        public string password_tch { get; set; }
    
        public virtual ICollection<SubjectOfTeacher> SubjectOfTeacher { get; set; }
    }
}
