//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinLogin
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ExamTicket_dbEntities : DbContext
    {
        public ExamTicket_dbEntities()
            : base("name=ExamTicket_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Groups> Groups { get; set; }
        public virtual DbSet<LogStudents> LogStudents { get; set; }
        public virtual DbSet<Questions> Questions { get; set; }
        public virtual DbSet<SubjectOfTeacher> SubjectOfTeacher { get; set; }
        public virtual DbSet<Subjects> Subjects { get; set; }
        public virtual DbSet<Teachers> Teachers { get; set; }
    
        public virtual ObjectResult<output_subject_of_teacher_Result> output_subject_of_teacher(Nullable<int> var_id)
        {
            var var_idParameter = var_id.HasValue ?
                new ObjectParameter("var_id", var_id) :
                new ObjectParameter("var_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<output_subject_of_teacher_Result>("output_subject_of_teacher", var_idParameter);
        }
    }
}
